{% set name = "sqsgenerator" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dgehringer/sqsgenerator/archive/v{{ version }}-rc.1.tar.gz
  sha256: c22b6de9c0eb76917abb3f641516339f62369e1676f0e6f9b79dc32b757546d9


build:
  number: 0
  entry_points:
    - sqsgen = sqsgenerator.cli:cli
  script:
    - export CMAKE_GENERATOR=Ninja  # [unix]
    - export CMAKE_CXX_COMPILER=$CXX  # [unix]
    - export CMAKE_C_COMPILER=$CC  # [unix]
    - rm -rf vcpkg
    - git clone https://github.com/microsoft/vcpkg.git
    - cd vcpkg && ./bootstrap-vcpkg.sh && cd ..  # [unix]
    - cd vcpkg && bootstrap-vcpkg.bat && cd ..  # [win]
    - cd python && {{ PYTHON }} -m pip install . -vv
  script_env:
    - VCPKG_DISABLE_METRICS=1
  skip: true  # [py<39]

requirements:
  build:
    - pip
    - python
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - numpy
    - pybind11
    - scikit-build-core
    - mypy
    - cmake
    - ninja
    - make
    - tar  # [linux]
    - unzip  # [linux]
    - curl  # [linux]
    - zip  # [linux]
    - pkg-config  # [linux]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - pip
    - python
    - numpy
    - scikit-build-core

  run:
    - python
    - click
    - numpy

test:
  imports:
    - sqsgenerator
  source_files:
    - tests
  requires:
    - pytest
    - ase
    - pymatgen
  commands:
    - pip check
    - cd python/tests && pytest --import-mode=importlib


about:
  home: https://github.com/dgehringer/sqsgenerator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A command line tool written in Python/C++ to generate SQS structures

  description: |
    This package is a Special Quasirandom Structure generator written 
    in Python3/C++
  doc_url: https://sqsgenerator.readthedocs.io/en/latest
  dev_url: https://github.com/dgehringer/sqsgenerator

extra:
  recipe-maintainers:
    - jan-janssen
    - dgehringer
