{% set name = "sqsgenerator" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/dgehringer/sqsgenerator.git
  git_rev: v{{ version }}-rc.1


build:
  number: 0
  entry_points:
    - sqsgen = sqsgenerator.cli:cli
  script: |
    git submodule update --init
    {{ PYTHON }} -m pip install ./python -vv
  skip: true  # [py<39]

requirements:
  build:
    - pip
    - python
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - numpy
    - pybind11
    - scikit-build-core
  host:
    - pip
    - git
    - python
    - pybind11
    - numpy
    - mypy
    - scikit-build-core
  run:
    - python
    - click
    - numpy

test:
  imports:
    - sqsgenerator
  source_files:
    - tests
  requires:
    - pytest
    - ase
    - pymatgen
  commands:
    - pip check
    - pytest
    - pytest ./python/tests --import-mode=importlib


about:
  home: https://github.com/dgehringer/sqsgenerator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A command line tool written in Python/C++ to generate SQS structures

  description: |
    This package is a Special Quasirandom Structure generator written 
    in Python3/C++
  doc_url: https://sqsgenerator.readthedocs.io/en/latest
  dev_url: https://github.com/dgehringer/sqsgenerator

extra:
  recipe-maintainers:
    - jan-janssen
    - dgehringer
