{% set name = "sqsgenerator" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dgehringer/sqsgenerator/archive/v{{ version }}-rc.2.tar.gz
  sha256: a951a4a878930133b4201d84621a992e568370281c47d8e995e4a4f49094d7ab


build:
  number: 0
  entry_points:
    - sqsgen = sqsgenerator.cli:cli
  script: |
    git clone https://github.com/microsoft/vcpkg.git
    {% if win %}
    vcpkg\bootstrap-vcpkg.bat
    {{ PYTHON }} -m pip install python\ -v --no-deps --no-build-isolation
    {% else %}
    vcpkg/bootstrap-vcpkg.sh
    export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"  # [unix]
    export CMAKE_ARGS="-DCMAKE_POLICY_VERSION_MINIMUM=3.5 ${CMAKE_ARGS}"  # [ppc64le]
    {{ PYTHON }} scripts/patch-pyproject.py $SRC_DIR/python/pyproject.toml  # [ppc64le]
    {{ PYTHON }} -m pip install python/ -v --no-deps --no-build-isolation
    {% endif %}

requirements:
  build:
    - make  # [unix]
    - cmake >=3.27.0
    - ninja
    - toml # [ppc64le]
    - tar  # [linux]
    - unzip  # [linux]
    - curl  # [linux]
    - zip  # [linux]
    - pkg-config  # [linux, osx]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform and not win]
    - python  # [build_platform != target_platform and not win]
    - scikit-build-core  # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]
  host:
    - pip
    - ninja  # [win]
    - numpy
    - python
    - pybind11 >=2.10.0
    - scikit-build-core

  run:
    - numpy
    - click
    - python
    - {{ pin_compatible('libcxx', min_pin='x.x', max_pin='x.x') }}  # [osx]

test:
  imports:
    - sqsgenerator

about:
  home: https://github.com/dgehringer/sqsgenerator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A command line tool written in Python/C++ to analyse short-range order or generate SQS structures

  description: |
    This package is a Special Quasirandom Structure generator written 
    in Python3/C++
  doc_url: https://sqsgenerator.readthedocs.io/en/latest
  dev_url: https://github.com/dgehringer/sqsgenerator

extra:
  recipe-maintainers:
    - jan-janssen
    - dgehringer
