{% set name = "sqsgenerator" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dnoeger/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 85407d2525947cd9eaab5e4e92ee84c568078e1967ffbd70c3733961269cfc7d
  patches:
    - pymatgen.patch

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<35]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - gmp
    - pymatgen
  run:
    - python
    - pip
    - cython
    - gmp
    - pymatgen

test:
  imports:
    - sqsgenerator
  commands:
    - pip check

about:
  home: https://github.com/dnoeger/sqsgenerator
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: A command line tool written in Python/Cython for finding optimized SQS structures

  description: |
    This package is a Special Quasirandom Structure generator written 
    in Python3/Cython. Please note that the programm currently only 
    works with Python 3.
  doc_url: https://github.com/dnoeger/sqsgenerator
  dev_url: https://github.com/dnoeger/sqsgenerator

extra:
  recipe-maintainers:
    - jan-janssen
    - dgehringer
