{% set name = "sqsgenerator" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dgehringer/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6bd8299e50860d47cdec99809e006b5caa5c4c9774fe189b85374ebd2bbf88ba
  patches:
    - pycompat.patch

build:
  number: 1
  entry_points:
    - sqsgen = sqsgenerator.cli:cli
  script_env:
    - CMAKE_CXX_FLAGS=-O2 -DNDEBUG  # [not win]
    - CMAKE_CXX_FLAGS=-O2 -DNDEBUG  -fpermissive  # [osx]
    - CMAKE_CXX_FLAGS=/O2 /DNDEBUG /MD /Zc:twoPhase- /DBOOST_PYTHON_STATIC_LIB /DBOOST_NUMPY_STATIC_LIB  # [win and py<=38]
    - CMAKE_CXX_FLAGS=/O2 /DNDEBUG /MD /Zc:twoPhase- /DBOOST_PYTHON_STATIC_LIB /DBOOST_NUMPY_STATIC_LIB /DHAVE_SNPRINTF  # [win and py>=39]
    - SQS_CMAKE_VERBOSE_MAKEFILE=ON  # [win]
    - SQS_FORWARD_WHITELIST=CMAKE_PREFIX_PATH  # [win]
    - SQS_CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<35]

requirements:
  build:
    - pip
    - six
    - make           # [unix]
    - cmake >=3.12.0
    - ninja          # [win]
    - numpy
    - python
    - libboost-python-devel
    - libboost-devel
    - libcxx <16     # [osx]
    - llvm-openmp    # [osx]
    - libgomp        # [linux]
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - six
    - ninja  # [win]
    - numpy
    - python
    - libboost-python-devel
    - libboost-devel
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - libcxx <16  # [osx]
  run:
    - pip
    - six
    - rich
    - numpy
    - click
    - python
    - pyyaml
    - frozendict
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('libcxx', min_pin='x.x', max_pin='x.x') }}  # [osx]

test:
  imports:
    - sqsgenerator
  commands:
    - pip check

about:
  home: https://github.com/dgehringer/sqsgenerator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A command line tool written in Python/C++ to analyse short-range order or generate SQS structures

  description: |
    This package is a Special Quasirandom Structure generator written 
    in Python3/C++
  doc_url: https://sqsgenerator.readthedocs.io/en/latest
  dev_url: https://github.com/dgehringer/sqsgenerator

extra:
  recipe-maintainers:
    - jan-janssen
    - dgehringer
