{% set name = "sqsgenerator" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dnoeger/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: feca0e549d0084fbc96b00afda8035c38fbcb09c1825780025af4c7954da890c

build:
  number: 0
  script_env:
    - SQS_Boost_USE_STATIC_LIBS=ON
    - SQS_CMAKE_CXX_FLAGS="-static-libstdc++"
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<35]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - libboost
    - py-boost
    - numpy
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - pip
    - python
    - libboost
    - py-boost
    - numpy
  run:
    - rich
    - click
    - python
    - pyyaml
    - numpy
    - attrdict
    - frozendict
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

test:
  imports:
    - sqsgenerator
  commands:
    - pip check

about:
  home: https://github.com/dgehringer/sqsgenerator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A command line tool written in Python/C++ for finding optimized SQS structures

  description: |
    This package is a Special Quasirandom Structure generator written 
    in Python3/C++
  doc_url: https://sqsgenerator.readthedocs.io/en/latest
  dev_url: https://github.com/dgehringer/sqsgenerator

extra:
  recipe-maintainers:
    - jan-janssen
    - dgehringer
