travis:
  secure:
    BINSTAR_TOKEN: GDODHaMTRFBPUlI6PnHV/M2fH9g1zJxlu1Cixb2AM0pNGDUsmC3SyKQ1mMZqz+/n+MxDA4xR6ghS8uqfDclC55liH9cT2axqxGJmtyNtDh1lQusxKXpbBfB0GdkVJ8sHzjsH2bNBKkSwjX5BJf/kZGcAsiGG9f2bgBC8J7Cxc51xgRaJon3ovL3wMATZFbxfc5nYOXbWAtmoEJa4NdqxOER/EJmsVSfnAVhrDd0poSa4Dlj6Yvofz39lDX3V2skEbPi6EI66dKhxrzIF0vJzwKJ7bztMpM4u33zULCvtS0qG0xxHeF1MsGmymsUfbe4paWBDayM7GkQ7NM0mFX3A4TxA+GLIJKQ4wNtnJv+izenUZgXPha4qsXYTQ8z5bGPyh2glsEVWCRWCO5mdblzWamRmZ1T1jgWynhBiHkqYq+SJd0Mu7sG8XA5O6fjRwn5f5l7iGTouQDkE/kLzuH+y3jJTJBWmKoYGbrSW5vP+Tfn9Ia6V1+6WjtdlbgeEz1oi6446W1lzi9NUytCfIjvZRDLy+8sBJTA7vi2MnioNo3ymskr2m02ydy4vBIuthmKUUJkV7G1YJ3N6y/RrZOIGs9Vz/mcZVZcAjHM8I6sREpvhwyIhJ+l7Uvedhjo+6gfHThV9k7Gm51n+L8boqbbsxdEzy+wu9G+ODoz45WpGgYo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
